language: ruby
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0

before_install:
  - gem install bundler

gemfile:
  - gemfiles/activesupport-4.0.gemfile
  - gemfiles/activesupport-4.1.gemfile
  - gemfiles/activesupport-4.2.gemfile
